### ISSUE TITLE
I get isothermal profile, instaed of adiabatic

### ISSUE THREAD

**Issue by Michlozz** [Huang-CL/Magrathea#12]
Hello again.
I gave up on polynomial method. There are too much trouble with this approximation. Mostly the problem is unexpected behavior on edges of different regions.
No instead I read directly from a table. I created global variables,  arrays named:    T_QEOS, P_QEOS , rho_QEOS,  U_QEOS, S_QEOS
[QEOS_tableTPrhoUS.txt](https://github.com/Huang-CL/Magrathea/files/13364256/QEOS_tableTPrhoUS.txt)
And I load them in the begging of the run.

_In EOSlist.cpp I have:_
```
double Si_QEOS_array[][2] = {{0,5}, {1, 27.36}, {5, mSi+2*mO} };
EOS *Si_QEOS = new EOS("Rock-H20-mix (QEOS)", Si_QEOS_array, sizeof(Si_QEOS_array)/2/sizeof(Si_QEOS_array[0][0]));


...
double S_Mix(double rho, double T){
 return S_Si_QEOS(rho,T);
}
double S_Si_QEOS(double rho, double T){
... reading from table, few interpolations
    S= (something)// in erg/(gram*K)
    S= S/(3.0*8.31446261815324e7 ); // 3 molecules, gas constant
}
```
_In EOS.cpp I have:_
```

double EOS::density(double P, double T, double rho_guess)
if(eqntype == 5){
		return  Rho_QEOS(double T, double P);
}
...
}
double Rho_QEOS(double T, double P) {
...reading from table, few interpolations
rho= (something) 
}
```

_In main.cpp:_

`  Si_QEOS->modify_extern_entropy(S_Mix);`

(I hope I didn't forget to write something important)

Now for some reason, the results are wrong: the profile is almost completely isothermal. So there is some bug in what I'm doing.
I try to find where can be a trouble. 
How does the program "know" to be adiabatic? 

<img src="https://github.com/Huang-CL/Magrathea/assets/113346451/3dd142e2-0081-48de-860b-f62a400e6b97" width="350">

Here I plot s as a function of P and T. This line was calculated then I take P and T from Magrathea output and calculate s for each point in Matlab (calculating via interpolation in table). It seems like the T is increasing very very slowly, but more important: **s isn't constant**. What can be the problem? 
Do you have a way to output the value of s in each layer?

**Comment by Huang-CL** [comment]
After a few days of checking, I still couldn't figure out what could go wrong.  There are a few changes that might improve efficiency, but let's put the issue of efficiency aside for the moment.

`
How does the program "know" to be adiabatic?
`

If you set the isothermal flag to true at line 251, 423 and several repeated occurrences in hydro.cpp, the value of the thermal tag will be set to 0.  At line 85 and 136, if the thermal tag is 0, the temperature gradient will be fixed at 0, or isothermal.

Even when isothermal flag is set to false, if the phase does not include enough input to calculate the temperature gradient, the thermal tag will be set to 4. And the output will also be isothermal.

In your case, the thermal tag should be 1, which is set at line 29 in EOS.h.  So the temperature profile should not be isothermal.

`
Do you have a way to output the value of s in each layer?
`
I just pushed a small modification to the code that print entropy in the final output file if the `debug` tag is set to true.  Or simply you can call `Phase->entropy(rho[i],T[i])` wherever you want to access the entropy.  See line 1370 in hydro.cpp of the recent commit for example.

**Comment by Huang-CL** [comment]
I tested this algorithm with a functional entropy expression and everything looks correct. 

Will the interpolating function output an approximately smooth result? If it is very unsmooth, at the very least, it will seriously affect the speed of the computation and may even cause the program to crash.

**Comment by DavidRRice** [comment]
Closed after confirming they found the issue.
