### ISSUE TITLE
Where exactly the code reads EOS from a file?

### ISSUE THREAD

**Issue by Michlozz** [Huang-CL/Magrathea#7]
Hi,

My goal now is to replace the EOS table with a one I have. In the meanwhile:
1) I created a file named "Test_Si.txt" in "tabulated" folder (temporal test EOS file)
2) in the file "EOSlist.h" I added " , *_Si_QEOS_"
3) in the file "EOSlist.ccp" I added a line "_EOS *Si_QEOS = new EOS("Si (test)", "./tabulated/Test_Si.txt");_"
4) in the file "phase.ccp" under "_EOS* find_Si_phase(double P, double T)"_ I added "_return Si_QEOS_"

It worked: compiles and runs.

Now, as a next step I try to find the exact place there the code reads P and Rho from this "Test_Si.txt" file. I want to place there a breakpoint. As the format of the EOS file I'll use differs from yours, I what to modify/correct the reading procedure to my needs.

**Comment by Huang-CL** [comment]
They are at lines 156-205 in the EOS.cpp.
