### ISSUE TITLE
Adding new EOS fucntion

### ISSUE THREAD

**Issue by Michlozz** [Huang-CL/Magrathea#9]
Hello again!

I decided to "start over", as reading from a table in each iteration took too much time. And I got some strange bugs in the code, with density jumps.  So instead of reading form a table, I found numerical fits for my function. The function is approximately piecewise polynomial. So no interpolation, just put in a formula from now.
Namely, my function looks like:
```

double QEOS(double T, double rho) {
    double P;
    double p00,p10,p01,p20,p02,p11,p12,p21,p30,p03;
    T= T*8.61697e-8; // form K to Kev
    T=log10(T); //to Log scale
    rho=log10(rho);// (assuming cgs) to Log scale
    
    if (rho<=0.4 && T<4.2){ //region 1
        p00=-8.773;
        p10=4.017;
        p01=0;
        p20=0.4632;
        p11=0;
        p02=0;
        p30=0.02391;
        p21=0;
        p12=0;
        p03 = 0;}
 // ....(missing part)....
   if (T>-3 && rho<=0.4) {//region 4
            p00 =      -1.364;
            p10 =       0.9002;
            p01 =      0.9935;
            p20 =      -0.2522;
            p11 =      0.05099;
            p02 =      -0.003507;
            p30 =      -0.03374;
            p21 =      0.009997;
            p12 =      -0.0004553;
            p03 =      0;
    }
    P= p00 + p10*T + p01*rho + p20*T*T + p11*T*rho + p02*rho*rho +p21*T*T *rho  +   p12*T*rho*rho + p30*T*T*T+ 03*rho*rho*rho;
    P= pow(10.0,P); // in 10^4 megabars
    P= P* 1e16; // back to cgs (dynes * cm^-2)
	return P;
}
```
The EOS itself has phase separation and different regimes. This EOS is supposed to be used for mantle only (rock).
Fist of all:  the table was in log10 scale, pentapascals and KeV, so I made a conversion. The ** input of the function is in Kelvin and gr*cm^-3, the output is dynes * cm^-2**.  Are the units correct?

Second, and more important:
I will use the latest version of your code. What are the changes I need to to to force the code use my EOS for the mantle? 
So far, if I understand: 

1. add the code of QEOS itself to EOS.cpp, just after the end of "_double EOS::Press(double rho, double T)_" function. 
2. add a line "_double QEOS(double T, double rho);_" in EOS.h, line 159
3. add _double Si_QEOS_array[][2] = {{0,5}, {1, 40}, {5, mSi}};
EOS *Si_QEOS = new EOS("Si (QEOS)", Si_QEOS_array, sizeof(Si_QEOS_array)/2/sizeof(Si_QEOS_array[0][0]));_ to EOSList.cpp
4. In phase.cpp, in function _EOS* find_Si_phase(double P, double T)_ I replace both EOS'es with "return QEOS;"

so far, so good? 
I get an error "src/phase.cpp:386:11: error: cannot convert ‘double (*)(double, double)’ to ‘EOS*’ in return", so I missed some step.

Am I doing it right? If not, what should I do?

Thanks a lot.

**Comment by DavidRRice** [comment]
Hi! Glad you are trying a function, we find this much more useful than porting around tables for many cases. The last step which may be the only think your missing is adding the new EOS Si_QEOS to the header file EOSlist.h. Do you have the updated code on your fork? I can take a look if putting the new EOS in the header doesn't fix it.

**Comment by Huang-CL** [comment]
The if conditions in your `QEOS` don't look correct to me.  Although it could have come from the fact that you didn't paste the complete code, I would still suggest that you double-check it.

The output pressure unit of `Press` function is GPa, not dynes * cm^-2.  

I suggest you add the `QEOS` function in front of `Press`.  Then add something like the following into `Press`.
```
  case 5:			// QEOS
    P = QEOS(T, rho);
    break;
```
It's not required to include `double QEOS(double T, double rho);` in EOS.h.  But there's no harm in adding it.
In phase.cpp, you should return `Si_QEOS`, not `QEOS`.

**Comment by Michlozz** [comment]
Thanks both, it seem to work now!
So to make sure: the **output units of P=function(rho)** ( for all the cases in " EOS::Press(double rho, double T)" ) are **GPa?**

And one more thing: the code seem to work form outside in, correct? It decides to end the atmosphere and start the mantle according to the mass vector on Main.cpp, if I understand correctly. 
So my question is: What is conserved in the boundary layer? Is it P, meaning that "P(upper rocky layer)==P(lowest water layer)"?

**Comment by Huang-CL** [comment]
> So to make sure: the output units of P=function(rho) ( for all the cases in " EOS::Press(double rho, double T)" ) are GPa?
Yes, this is correct.  The general rule of thumb is that pressure unit GPa is used at the user interface.  The cgs pressure unit is more commonly used for internal calculations.

The solving method is described in section 3.1 of our paper. It includes both outside-in and inside-out integrations.  P, m and r are conserved.   T is also conserved unless Tgap is set.

**Comment by Michlozz** [comment]
Thanks!
